### ISSUE TITLE
[建議] 關於新聞部分

### ISSUE THREAD

**Issue by axionl** [ResistanceCN/website#1]
## 新聞詳情

![screenshot from 2017-07-23 20-16-50](https://user-images.githubusercontent.com/8396456/28499251-ecf9a91a-6fe3-11e7-95df-875e237709f8.png)

- 新聞頁面的內容部分距離卡片邊緣太近，宜繼續向內收縮

- 代碼段與跨全卡片，容易起到不應有的段落分割效果，不利於文本邏輯的梳理，比如章和小節等，建議與文字同寬

- 鏈接顏色建議選用藍色，玫紅色有輕微影響閱讀體驗

## 新聞展示卡片

![screenshot from 2017-07-23 20-22-41](https://user-images.githubusercontent.com/8396456/28499281-b6a17220-6fe4-11e7-8f19-9869507e59d2.png)

- 按照一般使用邏輯，`READ MORE` 控件應該是在卡片右手邊位置

**Comment by balthild** [comment]
是否考慮將正文頁面更改爲類似於 https://material.io/guidelines/layout/responsive-ui.html 的樣式。即去除 Z 高度爲 1dp 的卡片，直接把內容鋪到畫布上。

**Comment by axionl** [comment]
如果是完全平鋪的話需要考慮新聞內容之間的區分，以及新聞與背景色之間的區分，上述方案中使用的是灰色背景加白色卡片方案，白色卡片周圍陰影由於高度下調，形成灰色邊框可以達到區分效果。

另外關於頁面之間的過度不知是否有意實現，不過可能涉及到頁內加載。若不好實現的話可以不做考慮。
